# Generated by Django 3.0 on 2019-12-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
